CREATE DATABASE IF NOT EXISTS MUSIC_DATABASE;

USE MUSIC_DATABASE;

SELECT * FROM ALBUM;
SELECT * FROM ALBUM2;
SELECT * FROM ARTIST;
SELECT * FROM CUSTOMER;
SELECT * FROM EMPLOYEE;
SELECT * FROM GENRE;
SELECT * FROM INVOICE_LINE;
SELECT * FROM INVOICE;
SELECT * FROM MEDIA_TYPE;
SELECT * FROM PLAYLIST_TRACK;
SELECT * FROM PLAYLIST;
SELECT * FROM EMPLOYEE;
SELECT * FROM TRACK;


