# Q-6 Write query to return the email, first name, last name, and genre of all the rock music listeners. 
# Return your list ordered alphabetically by email starting with A.

USE MUSIC_DATABASE;

SHOW TABLES;

SELECT EMAIL, FIRST_NAME, LAST_NAME
FROM CUSTOMER
JOIN INVOICE ON CUSTOMER.CUSTOMER_ID = INVOICE.CUSTOMER_ID
JOIN INVOICE_LINE ON INVOICE.INVOICE_ID = INVOICE_LINE.INVOICE_ID
WHERE TRACK_ID IN (SELECT TRACK_ID 
FROM TRACK
JOIN GENRE
ON TRACK.GENRE_ID = GENRE.GENRE_ID
WHERE GENRE.NAME LIKE 'ROCK')
ORDER BY EMAIL ASC;

SELECT * FROM TRACK;

SELECT * FROM GENRE
WHERE NAME = "ROCK";
