# Let's invite the artist who have written the most rock music in our dataset. 
# Write a query that returns the artist name and total track count of top 10 rock bands.

USE MUSIC_DATABASE;

SHOW TABLES;
SELECT * FROM ARTIST;

SELECT ARTIST.ARTIST_ID, ARTIST.NAME, COUNT(ARTIST.ARTIST_ID) AS 'NUMBER_OF_SONGS'
FROM TRACK
JOIN ALBUM ON ALBUM.ALBUM_ID = TRACK.ALBUM_ID
JOIN ARTIST ON ARTIST.ARTIST_ID = ALBUM.ALBUM_ID
JOIN TRACK ON TRACK.GENRE_ID = GENRE.GENRE_ID
WHERE GENRE.NAME LIKE 'ROCK'
GROUP BY ARTIST.ARTIST_ID
ORDER BY NUMBER_OF_SONGS DESC
LIMIT 10;

SELECT * FROM TRACK;

SELECT ALBUM_ID, NAME, COUNT(ARTIST.ARTIST_ID) AS 'NUMBER OF SONGS'
FROM TRACK
JOIN ALBUM ON ALBUM.ALBUM_ID = TRACK.ALBUM_ID
JOIN ARTIST ON ARTIST.ARTIST_ID = ALBUM.ALBUM_ID
JOIN TRACK ON TRACK.GENRE_ID = GENRE.GENRE_ID
WHERE GENRE.NAME LIKE 'ROCK'
GROUP BY ARTIST.ARTIST_ID
ORDER BY NUMBER_OF_SONGS DESC
LIMIT 10;